export const lightTheme = {
  dark: false,
  colors: {
    background: "#FFFFFF",
    primary: "#007AFF",
    secondary: "#2FA2B9",
    text: "#0A0909",
    card: "#FFFFFF",
    border: "#E5E7EB",
    notification: "#FFFFFF",
    medium: "#D1D5DB",
    redText: "#EC7669",
    placeholderText: "#9B9B9B",
    bodyText: "#6B7280",
    highlightText: "#0A6375",
    highlightBorder: "#2FA2B9",
    inputFormBackground: "#F8F8F6",
    alertBase: "#F75555",
    alertSecondary: "#EF4444",
    bottomBorder: "#D1D5DB",
  },
};
